/elevation_mapping_node:
  ros__parameters:
    pointcloud_channel_fusions:
      rgb: 'color'
      default: 'average'

    image_channel_fusions:
      rgb: 'color'
      default: 'exponential'
      feat_.*: 'exponential'
    
      GET_channel_fusions:
        dig_difficulty: 'latest' # 'latest' fusion is used for the 'dig_difficulty' channel since we don't have uncertainty yet #deprecated
        d: 'latest' # 'latest' fusion is used for the 'd' channel as it is just used for visualization
        MeanCuttingForceMag: 'latest' # 'latest' fusion is used for the 'MeanCuttingForceMag' channel as it is just used for visualization
        default: 'bayesian_inference'

    subscribers:
      front_cam:
        topic_name: '/intel_realsense_r200_depth/points'
        data_type: pointcloud
        channels: ['rgb']
        noise_model_name: SLS_old
        SLS_old_noise_model_params:
          sensor_noise_factor: 0.05                       # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
      simple_flat_blade:
        data_type: GET
        GET_model_name: 'simple_blade'
        topic_name: '/odom'
        blade_frame: 'base_footprint'
        max_translation_m: 0.2
        max_time_s: 0.5
        max_rotation_deg: 10.0
        soil_prop_est_net_checkpoint_path: './lightning_logs/Elevation-Mapping1-phys_inf/lightning_logs/version_42/checkpoints/last.ckpt'
        simple_blade_GET_params:
          blade_width: 0.5
          blade_height: 0.25

    publishers:
      elevation_map_raw:
        layers: ['elevation', 'traversability', 'variance', 'elevation_loose', 'elevation_compact', 'rgb']
        # layers: ['elevation', 'traversability', 'variance','rgb', 'elevation_loose', 'elevation_compact']
        basic_layers: ['elevation']
        fps: 5.0
      elevation_map_filter:
        layers: ['min_filter', 'smooth', 'inpaint', 'elevation']
        basic_layers: ['min_filter']
        fps: 3.0