/elevation_mapping_node:
  ros__parameters:
    pointcloud_channel_fusions:
      rgb: 'color'
      default: 'average'

    image_channel_fusions:
      rgb: 'color'
      default: 'exponential'
      feat_.*: 'exponential'
    
      GET_channel_fusions:
        dig_difficulty: 'latest' # 'latest' fusion is used for the 'dig_difficulty' channel since we don't have uncertainty yet #deprecated
        d: 'latest' # 'latest' fusion is used for the 'd' channel as it is just used for visualization
        MeanCuttingForceMag: 'latest' # 'latest' fusion is used for the 'MeanCuttingForceMag' channel as it is just used for visualization
        default: 'bayesian_inference'

    subscribers:
        front_zed:
            topic_name: '/zed_multi/zed_front/point_cloud/cloud_registered'
            data_type: pointcloud
            channels: ['rgb']
            noise_model_name: SLS_old
            SLS_old_noise_model_params:
                sensor_noise_factor: 0.05                                             # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
            constant_noise_model_params:
                constant_variance: 0.01
            SLS_noise_model_params:
                a: 6.8e-3
                b: 28.0e-3
                c: 38.0e-3
                # d: (42e-3+2.0e-3)/2.0
                d: 22.0e-3
                Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
                Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
            LiDAR_noise_model_params:
                a: 0.012
                b: 6.8
                c: 0.81
                Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
                Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
        rear_zed:
            topic_name: '/zed_multi/zed_back/point_cloud/cloud_registered'
            data_type: pointcloud
            channels: ['rgb']
            noise_model_name: SLS_old
            SLS_old_noise_model_params:
                sensor_noise_factor: 0.05                                             # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
            constant_noise_model_params:
                constant_variance: 0.01
            SLS_noise_model_params:
                a: 6.8e-3
                b: 28.0e-3
                c: 38.0e-3
                # d: (42e-3+2.0e-3)/2.0
                d: 22.0e-3
                Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
                Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
            LiDAR_noise_model_params:
                a: 0.012
                b: 6.8
                c: 0.81
                Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
                Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
        simple_flat_blade:
          data_type: GET
          GET_model_name: 'simple_blade'
          topic_name: 'fake_odom'
          use_blade_odometry: false
          blade_frame: 'blade_edge_link'
          max_translation_m: 0.4
          max_time_s: 0.5
          max_rotation_deg: 10.0
          soil_prop_est_net_checkpoint_path: './lightning_logs/Elevation-Mapping1-phys_inf/lightning_logs/version_42/checkpoints/last.ckpt'
          simple_blade_GET_params:
            blade_width: 1.850
            blade_height: 0.76

    publishers:
      elevation_map_raw:
        # layers: ['elevation', 'traversability', 'variance', 'elevation_loose', 'elevation_compact', 'elevation_reference', 'rgb']
        layers: ['elevation', 'elevation_reference', 'rgb']
        # layers: ['elevation', 'traversability', 'variance','rgb', 'elevation_loose', 'elevation_compact']
        basic_layers: ['elevation']
        fps: 5.0
      elevation_map_filter:
        layers: ['min_filter', 'smooth', 'inpaint', 'elevation']
        basic_layers: ['min_filter']
        fps: 3.0