#### Basic parameters ########
resolution: 0.1                                 # resolution in m.
map_length: 15.0                                # map's size in m.
mahalanobis_thresh: 2.0                         # points outside this distance is outlier.
outlier_variance: 0.01                          # if point is outlier, add this value to the cell.
drift_compensation_variance_inler: 0.05         # cells under this value is used for drift compensation.
max_drift: 0.1                                  # drift compensation happens only the drift is smaller than this value (for safety)
drift_compensation_alpha: 0.1                   # drift compensation alpha for smoother update of drift compensation
variance_inflation_rate: 0.001                  # Rate of inflation of variance for drift compensation in units of m^2/s
max_variance: 100.0                             # maximum variance for each cell.
initial_variance: 1000.0                        # initial variance for each cell.
traversability_inlier: 0.9                      # cells with higher traversability are used for drift compensation.
dilation_size: 3                                # dilation filter size before traversability filter.
wall_num_thresh: 20                             # if there are more points than this value, only higher points than the current height are used to make the wall more sharp.
min_height_drift_cnt: 100                       # drift compensation only happens if the valid cells are more than this number.
position_noise_thresh: 0.01                     # if the position change is bigger than this value, the drift compensation happens.
orientation_noise_thresh: 0.01                  # if the orientation change is bigger than this value, the drift compensation happens.
position_lowpass_alpha: 0.2                     # lowpass filter alpha used for detecting movements.
orientation_lowpass_alpha: 0.2                  # lowpass filter alpha used for detecting movements.
min_valid_distance: 0.5                         # points with shorter distance will be filtered out.
max_height_range: 1.0                           # points higher than this value from sensor will be filtered out to disable ceiling.
ramped_height_range_a: 0.3                      # if z > max(d - ramped_height_range_b, 0) * ramped_height_range_a + ramped_height_range_c, reject.
ramped_height_range_b: 1.0                      # if z > max(d - ramped_height_range_b, 0) * ramped_height_range_a + ramped_height_range_c, reject.
ramped_height_range_c: 0.2                      # if z > max(d - ramped_height_range_b, 0) * ramped_height_range_a + ramped_height_range_c, reject.
update_variance_fps: 5.0                        # fps for updating variance.
update_pose_fps: 10.0                           # fps for updating pose and shift the center of map.
time_interval: 0.1                              # Time layer is updated at this interval.
map_acquire_fps: 5.0                            # Raw map is fetched from GPU memory in this fps.
publish_statistics_fps: 1.0                     # Publish statistics topic in this fps.

max_ray_length: 10.0                            # maximum length for ray tracing.
cleanup_step: 0.0                               # subtitute this value from validity layer at visibiltiy cleanup. Setting to 0 to disable invalidation of a cell
cleanup_cos_thresh: 0.1                         # subtitute this value from validity layer at visibiltiy cleanup.

safe_thresh: 0.7                                # if traversability is smaller, it is counted as unsafe cell.
safe_min_thresh: 0.4                            # polygon is unsafe if there exists lower traversability than this.
max_unsafe_n: 10                                # if the number of cells under safe_thresh exceeds this value, polygon is unsafe.

overlap_clear_range_xy: 4.0                     # xy range [m] for clearing overlapped area. this defines the valid area for overlap clearance. (used for multi floor setting)
overlap_clear_range_z: 2.0                      # z range [m] for clearing overlapped area. cells outside this range will be cleared. (used for multi floor setting)

map_frame: 'odom'                               # The map frame where the odometry source uses.
base_frame: 'base_footprint'                              # The robot's base frame. This frame will be a center of the map.
corrected_map_frame: 'odom'

#### Feature toggles ########
enable_edge_sharpen: true
enable_visibility_cleanup: false
enable_drift_compensation: true
enable_overlap_clearance: false
enable_pointcloud_publishing: false
enable_drift_corrected_TF_publishing: false
enable_normal_color: false                      # If true, the map contains 'color' layer corresponding to normal. Add 'color' layer to the publishers setting if you want to visualize.

#### Traversability filter ########
use_chainer: false                              # Use chainer as a backend of traversability filter or pytorch. If false, it uses pytorch. pytorch requires ~2GB more GPU memory compared to chainer but runs faster.
# weight_file: '$(rospack find elevation_mapping_cupy)/config/core/weights.dat'               # Weight file for traversability filter

#### Ground Engaging Tool (GET) Parameters ########
# TODO: Tune all of these parameters
move_dir_normal_weight: 0.5
# TODO: Consider moving some of these parameters to the parameters.yaml file as they should be the same for all blades
swell_factor: 1.3 # TODO: Make parameter (use something reasonable). Set to 1 for no swell
spill_factor: 0.0 # Proporation of loose material moved during a sweep that is spilled
compacted_soil_moist_unit_weight: 14635.91630769231 # Currently set to 50% relative density of loam in Vortex
l_fit_max: 1.0 # The maximum distance from the blade to find surface points for finding surface plane
surf_interp_coeff: 3.0 # Parameter of exponential function weighting distance from blade for surface fit
l_surcharge_max: 1.0 # The maximum distance from the blade to include loose soil in the surcharge calculation
depth_weight_avg_coeff: 0.0 # Set to 0 for regular average
max_surcharge_vol_per_unit_width: -1.0 # 0.1-0.3 seems optimal? Units of m^2. Set to -1 to disable limit. Can think about as size of pile in front of blade, e.g. blade_height*surcharge_dist_x for rectangular
em_FEE_max_projection_dist: 0.5 # Maximum distance to extrapolate FEE params generation from last valid em data
use_soil_erosion: true # Use soil erosion or not
erosion_ROI_dx: 2.0 # Length of region around blade to consider for erosion
erosion_ROI_dy: 1.0 # Width of region around blade to consider for erosion (will be blade_width+erosion_ROI_dy)
loose_soil_cohesion : 25.0 # TODO: Set to reasonable Value Units of Pa. Cohesion of loose soil
loose_soil_phi : 0.26 # TODO: Set to reasonable value Units of radians. Internal friction angle of loose soil
# loose_soil_gamma : compacted_soil_moist_unit_weight*swell_factor
soil_erosion_alpha_min : 0.05 # Units of radians. Minimum angle of slope to consider for erosion
soil_erosion_maximum_dt: 0.1 # Maximum time step for erosion calculation in seconds. Making too large can cause poor behavior

#### Soil Property Estimation ########
use_soil_property_estimation: true             # Use soil property estimation or not., i.e. run the soil property estimation network and add the estimated soil properties to the map.
soil_prop_est_net_checkpoint_path: './lightning_logs/Elevation-Mapping1-phys_inf/lightning_logs/version_42/checkpoints/last.ckpt' # Path to the checkpoint of the soil property estimation network.
bayesian_soil_wedge_exp_weight_coeff: 1.0       # Coefficient for the exponential weight function used for the soil property estimation. w = exp(-coeff * (x_s-1)), where x_s is the normalized wedge depth.
min_soil_prop_marking_dist: 0.3                # All points less than this distance from the blade are marked with the soil properties estimated by the network.

#### Upper bound ########
use_only_above_for_upper_bound: false

#### Initializer ########
initialize_method: 'linear'                                         # Choose one from 'nearest', 'linear', 'cubic'
initialize_frame_id: ['base_footprint']   # One tf (like ['footprint'] ) initializes a square around it.
initialize_tf_offset: [0.0, 0.0, 0.0, 0.0]                          # z direction. Should be same number as initialize_frame_id.
dilation_size_initialize: 2                                         # dilation size after the init.
initialize_tf_grid_size: 0.5                                        # This is not used if number of tf is more than 3.
use_initializer_at_start: true                                      # Use initializer when the node starts.
initialized_variance: 1000.0                                        # Initialized variance for each cell. 

#### Plugins ########
# plugin_config_file: '$(rospack find elevation_mapping_cupy)/config/setups/vortex_simple_blade/plugin_config.yaml'