#### Channel Fusions ########
pointcloud_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'average'          # 'average' fusion is used for channels not listed here

additional_layers: []

#### Subscribers ########
subscribers:
  lidar_front: # Must match the observation key from the gym env
    topic_name: '/lidar/front/points'
    data_type: pointcloud
    noise_model_name: SLS_old
    SLS_old_noise_model_params:
      sensor_noise_factor: 0.05                       # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
    constant_noise_model_params:
      constant_variance: 0.01
    SLS_noise_model_params:
      a: 6.8e-3
      b: 28.0e-3
      c: 38.0e-3
      # d: (42e-3+2.0e-3)/2.0
      d: 22.0e-3
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
    LiDAR_noise_model_params:
      a: 0.012
      b: 6.8
      c: 0.81
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
  lidar_rear: # Must match the observation key from the gym env
    topic_name: '/lidar/rear/points'
    data_type: pointcloud
    noise_model_name: SLS_old
    SLS_old_noise_model_params:
      sensor_noise_factor: 0.05                       # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
    constant_noise_model_params:
      constant_variance: 0.01
    SLS_noise_model_params:
      a: 6.8e-3
      b: 28.0e-3
      c: 38.0e-3
      # d: (42e-3+2.0e-3)/2.0
      d: 22.0e-3
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
    LiDAR_noise_model_params:
      a: 0.012
      b: 6.8
      c: 0.81
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
  simple_flat_blade:
    data_type: GET
    GET_model_name: 'simple_blade'
    simple_blade_GET_params:
      blade_width: 3.164
      blade_height: 0.660
      # TODO: Tune all of these parameters
      move_dir_normal_weight: 0.5
      swell_factor: 1.0 # TODO: Make parameter (use something reasonable). Set to 1 for no swell
      spill_factor: 0.05 # Proporation of loose material moved during a sweep that is spilled
      compacted_soil_moist_unit_weight: 14635.91630769231 # Currently set to 50% relative density of loam in Vortex
      l_fit_max: 1.5 # The maximum distance from the blade to find surface points for finding surface plane
      surf_interp_coeff: 3.0 # Parameter of exponential function weighting distance from blade for surface fit
      l_surcharge_max: 1.0 # The maximum distance from the blade to include loose soil in the surcharge calculation
      depth_weight_avg_coeff: 0.0 # Set to 0 for regular average
      max_surcharge_vol_per_unit_width: 0.3 # 0.1-0.3 seems optimal? Units of m^2. Set to -1 to disable limit. Can think about as size of pile in front of blade, e.g. blade_height*surcharge_dist_x for rectangular
      em_FEE_max_projection_dist: 0.5 # Maximum distance to extrapolate FEE params generation from last valid em data