#### Channel Fusions ########
pointcloud_channel_fusions:
  rgb: 'color'                # 'color' fusion is used for the 'rgb' channel
  default: 'average'          # 'average' fusion is used for channels not listed here

additional_layers: []

#### Subscribers ########
subscribers:
  lidar_front: # Must match the observation key from the gym env
    topic_name: '/lidar/front/points'
    data_type: pointcloud
    noise_model_name: SLS
    SLS_old_noise_model_params:
      sensor_noise_factor: 0.05                       # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
    constant_noise_model_params:
      constant_variance: 0.01
    SLS_noise_model_params:
      a: 6.8e-3
      b: 28.0e-3
      c: 38.0e-3
      # d: (42e-3+2.0e-3)/2.0
      d: 22.0e-3
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]
  lidar_rear: # Must match the observation key from the gym env
    topic_name: '/lidar/rear/points'
    data_type: pointcloud
    noise_model_name: SLS
    SLS_old_noise_model_params:
      sensor_noise_factor: 0.05                       # point's noise is sensor_noise_factor*z^2 (z is distance from sensor).
    constant_noise_model_params:
      constant_variance: 0.01
    SLS_noise_model_params:
      a: 6.8e-3
      b: 28.0e-3
      c: 38.0e-3
      # d: (42e-3+2.0e-3)/2.0
      d: 22.0e-3
      Sigma_Theta_BS_diag: [1.0e-1, 1.0e-1, 1.0e-1]
      Sigma_b_r_BS_diag: [1.0e-3, 1.0e-3, 1.0e-3]